### ISSUE TITLE
In navigation.py:598 .. Attribute Error: 'function' object has no attribute 'im_func'

### ISSUE THREAD

**Issue by DGBlueWolf** [general-ai-challenge/Round1#1]
Running 

`python src/run.py src/tasks_config.sample.json -l learners.human_learner.ImmediateHumanLearner`

On Python 3.5 in a Windows, resulted in an attribute error in the middle of execution.

![attribute_error](https://cloud.githubusercontent.com/assets/15271252/22988777/44dcebd6-f381-11e6-9d12-0a5a5ba2218f.png)

I copied the config file and changed it at line 170 to include only that particular task, and was able to reproduce the error.

`"scheduler":`
`      {`
`         "type": "core.scheduler.RandomTaskScheduler",`
`         "args": {`
`         "tasks": [ "aj3"]`
`         }`
`    }`

Removing the `.im_func` in navigation.py:598 from `self.on_object_picked.im_func` fixed the issue for me.

**Comment by martinpoliak-goodai** [comment]
Hi  Blue Wolf, thanks for noticing this! 

The issue that you describe is related to the tasks that appear in the [original CommAI-env](https://github.com/facebookresearch/CommAI-env). We were considering whether to keep those tasks in the challenge code or not, but eventually decided to keep them to allow anyone interested to browse through the original tasks and get to know what Baroni, Mikolov et al. had in mind when developing the environment.

We will not support these tasks, as they are not related to the challenge. We think we did not stress this enough in the original README. That's why we've updated the README and removed the sample.json config file to avoid confusion.

Just to sum the changes in the README for you, the original tasks are not supported by us and if you find an issue there, you should report it in the original repository from Facebook. If you want to run the original tasks, you should use `--bit-mode` switch and preferably run in python 2.6+, as the tasks are not officially supported on python 3.

Hope this helps!
