### ISSUE TITLE
Evaluation tasks/curricula questions

### ISSUE THREAD

**Issue by MLanghof** [general-ai-challenge/Round1#14]
The challenge specifications go into depth on how a sequence of tasks is evaluated (and these steps are also evident from the python code in this repo). However, the specs also state (in A.1.6) that the publicly available task set is only one "curriculum", and that agents will be evaluated on various non-public curricula. That part makes sense, however the procedures regarding this are not made evident in the rest of the specs (including the graphics), which only talk about solving task sequences.

So here are questions regarding these missing specifications:
- Will agents be evaluated (and judged) on all non-public curricula?
- How many of those will there be?
- Will the agent have to solve all of them in the 24 hour period?*
- Is the "number of simulation steps" that agents are judged by the sum of the simulation steps needed in all curricula?
- What if different submitted agents manage to solve only some (different) curricula? Surely not all curricula are equally difficult, so how would judging work in this case?
- Are agents (and the environment) restarted between curricula or will the next curriculum start after the current one without any notice?

*The specs read as if agents will have to solve all the tasks, however I have seen GoodAI statements along the lines of "we don't know if anybody will be able to solve the challenge at all" - in the event that no agent can solve all (or any) of the tasks, how is the judging process going to look?

**Comment by martinpoliak-goodai** [comment]
Hi, good questions! Next time, please post this kind of question to the challenge forum so that more people can see it (https://discourse.general-ai-challenge.org/).
 
In the quantitative evaluation part:

- We plan to evaluate the agent on a single non-public evaluation curriculum of increasing difficulty.
- The performance on the public curriculum will not be considered.
- The agent should solve as many of the tasks (preferably all of them) from the non-public evaluation curriculum in as little total simulation steps as possible.
- As there's only one evaluation curriculum, there's no restarting of agents between curricula. Actually, you are invited to submit a pre-trained agent. The agent will not start from scratch on the evaluation curriculum, but it will be allowed to use the pre-trained knowledge.
- Your solution must exhibit the non-forgetting and gradual learning properties. This will be evaluated using combinations of tasks from the non-public evaluation curriculum.

Besides quantitative evaluation, there will also be the _qualitative_ evaluation, in which you can win a prize even without solving the evaluation curriculum if the jury assesses your solution as good/promising enough. Solving the public training curriculum may help in this leg of the challenge.

In case nobody solves the evaluation curriculum (in the quantitative evaluation part), we will most likely award only the qualitative prize.
